package midware

import (
	"strings"
	"time"

	"github.com/dgrijalva/jwt-go"
	"github.com/gin-gonic/gin"

	"use-gin/auth"
	"use-gin/config"
	"use-gin/errcode"
	"use-gin/handler"
)

func JWT() gin.HandlerFunc {
	// this jwtSecret is for /login, and the token is generated by server.
	jwtSecret := config.Conf().Auth.JWTSecret

	return func(c *gin.Context) {
		jwtToken := c.Query("jwt")

		if jwtToken == "" {
			jwtToken = c.Query("token")
		}

		if jwtToken == "" {
			authHeader := c.GetHeader("Authorization")
			if authHeader != "" {
				values := strings.Split(authHeader, " ")
				if len(values) != 2 || values[0] != "Bearer" {
					err1 := errcode.New(errcode.TokenInvalidError, nil)
					err1.Add("Request header 'Authorization' format invalid.")
					handler.SendResponse(c, err1, nil)

					c.Abort()
					return
				}
				jwtToken = values[1]
			}
		}

		if jwtToken == "" {
			err1 := errcode.New(errcode.TokenInvalidError, nil)
			err1.Add("no JWT(Json Web Token) found.")
			handler.SendResponse(c, err1, nil)

			c.Abort()
			return
		} else {
			payloadSegment := strings.Split(jwtToken, ".")[1]
			payload, err := auth.GetPayload(payloadSegment)
			if err != nil {
				err1 := errcode.New(errcode.TokenInvalidError, err)
				err1.Add("JWT validation failed.")
				handler.SendResponse(c, err1, nil)

				c.Abort()
				return
			}

			if secret, ok := auth.GetSecretOfAppkey(payload.Issuer); ok {
				// this jwtSecret is for api auth, and the token is generated by client(user) side.
				jwtSecret = secret
				jwtMaxLifetime := config.Conf().Auth.JWTMaxLifetime
				if payload.ExpiresAt-time.Now().Unix() > jwtMaxLifetime {
					err := errcode.New(errcode.TokenInvalidError, nil)
					err.Add("'exp': 'exceeds maximum allowed expiration'")
					handler.SendResponse(c, err, nil)

					c.Abort()
					return
				}
			}

			claims, err := auth.ParseJWT(jwtToken, jwtSecret)
			if err != nil {
				switch err.(*jwt.ValidationError).Errors {
				case jwt.ValidationErrorExpired:
					err1 := errcode.New(errcode.TokenInvalidError, err)
					err1.Add("JWT expired.")
					handler.SendResponse(c, err1, nil)
				case jwt.ValidationErrorSignatureInvalid:
					err1 := errcode.New(errcode.TokenInvalidError, err)
					err1.Add("JWT signature validation failed.")
					handler.SendResponse(c, err1, nil)
				default:
					err1 := errcode.New(errcode.TokenInvalidError, err)
					err1.Add("JWT validation failed.")
					handler.SendResponse(c, err1, nil)
				}

				c.Abort()
				return
			}

			// NOTE: handler function can be get username or appkey by c.Get("key")
			c.Set("key", claims.Issuer)
		}

		c.Next()
	}
}
